webtalk_init -webtalk_dir D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/voting_machine/voting_machine.sim/sim_1/behav/xsim/xsim.dir/voting_rule_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Feb  9 20:21:22 2019" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "a434f0f8-b8c9-4f08-8255-16f098eb95b4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "1402d5f89b8c4c5daf78cd111e703994" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3696 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.01_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "5456_KB" -context "xsim\\usage"
webtalk_transmit -clientid 1146608875 -regid "" -xml D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/voting_machine/voting_machine.sim/sim_1/behav/xsim/xsim.dir/voting_rule_behav/webtalk/usage_statistics_ext_xsim.xml -html D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/voting_machine/voting_machine.sim/sim_1/behav/xsim/xsim.dir/voting_rule_behav/webtalk/usage_statistics_ext_xsim.html -wdm D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/voting_machine/voting_machine.sim/sim_1/behav/xsim/xsim.dir/voting_rule_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
