# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.cache/wt} [current_project]
set_property parent.project_path {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {d:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/Control_Unit.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/Divider.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/imports/imports/sources_1/imports/new/bcd_to_7seg.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/imports/imports/sources_1/new/button_debouncer.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/imports/imports/sources_1/imports/new/clk_gen.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/comparator.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/imports/imports/sources_1/new/eight_bit_binary_to_decimal.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/four_bit_uint_divider_DP.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/imports/imports/new/led_mux.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/imports/imports/sources/mux2.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/nor4.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/or4.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/shift_register.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/subtractor.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/ud_counter.v}
  {D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/sources_1/new/Divider_fpga.v}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/constrs_1/new/Divider.xdc}}
set_property used_in_implementation false [get_files {{D:/Documents HDD/School/Cmpe 125/Cmpe 125 Projects/4_bit_uint_divider/4_bit_uint_divider.srcs/constrs_1/new/Divider.xdc}}]

set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top Divider_fpga -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Divider_fpga.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Divider_fpga_utilization_synth.rpt -pb Divider_fpga_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
